FROM yavzan/deepseek-distill-v1:base AS base

ARG HUGGINGFACE_ACCESS_TOKEN
ARG WORKDIR
WORKDIR ${WORKDIR}

RUN mkdir -p models/deepseek-r1-distill-qwen-7b
RUN pip install torch huggingface_hub


RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/deepseek-r1-distill-qwen-7b/config.json https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/resolve/main/config.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/deepseek-r1-distill-qwen-7b/generation_config.json https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/resolve/main/generation_config.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/deepseek-r1-distill-qwen-7b/model-00001-of-000002.safetensors https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/resolve/main/model-00001-of-000002.safetensors

RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/deepseek-r1-distill-qwen-7b/model-00002-of-000002.safetensors https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/resolve/main/model-00002-of-000002.safetensors
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/deepseek-r1-distill-qwen-7b/model.safetensors.index.json https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/resolve/main/model.safetensors.index.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/deepseek-r1-distill-qwen-7b/tokenizer.json https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/resolve/main/tokenizer.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/deepseek-r1-distill-qwen-7b/tokenizer_config.json https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B/resolve/main/tokenizer_config.json


COPY test_input.json .
EXPOSE 8188 8888

CMD ["bash", "/workspace/start.sh"]