FROM yavzan/deepseek-distill-v1:base AS base

ARG HUGGINGFACE_ACCESS_TOKEN
ARG WORKDIR
WORKDIR ${WORKDIR}

RUN mkdir -p models/deepseek-r1-distill-qwen-7b
RUN mkdir -p models/Meta-Llama-3-8B-Instruct
RUN mkdir -p models/tybert


RUN pip install torch huggingface_hub


RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/config.json https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/generation_config.json https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/generation_config.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/model-00001-of-00004.safetensors https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/model-00001-of-00004.safetensors
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/model-00002-of-00004.safetensors https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/model-00002-of-00004.safetensors
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/model-00003-of-00004.safetensors https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/model-00003-of-00004.safetensors
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/model-00004-of-00004.safetensors https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/model-00004-of-00004.safetensors
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/model.safetensors.index.json https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/model.safetensors.index.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/special_tokens_map.json https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/special_tokens_map.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/tokenizer.json https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/Meta-Llama-3-8B-Instruct/tokenizer_config.json https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/tokenizer_config.json

# ------------------------------------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------Trendyol/Tybert------------------------------------------------------------

RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/tybert/config.json https://huggingface.co/Trendyol/tybert/resolve/main/config.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/tybert/generation_config.json https://huggingface.co/Trendyol/tybert/resolve/main/generation_config.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/tybert/model.safetensors https://huggingface.co/Trendyol/tybert/resolve/main/model.safetensors
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/tybert/special_tokens_map.json https://huggingface.co/Trendyol/tybert/resolve/main/special_tokens_map.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/tybert/tokenizer.json https://huggingface.co/Trendyol/tybert/resolve/main/tokenizer.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/tybert/tokenizer_config.json https://huggingface.co/Trendyol/tybert/resolve/main/tokenizer_config.json
RUN wget --header="Authorization: Bearer ${HUGGINGFACE_ACCESS_TOKEN}" -O models/tybert/vocab.txt https://huggingface.co/Trendyol/tybert/resolve/main/vocab.txt
                
# ------------------------------------------------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------------------------------------------------

COPY script/start.sh ${WORKDIR}/start.sh
COPY script/start.sh .

COPY leader.json .
COPY test_input.json .
EXPOSE 8188 8888

CMD ["bash", "./start.sh"]